<?php

declare(strict_types=1);

namespace PHPolygon\Editor\Scene;

use BackedEnum;
use PHPolygon\Scene\Prefab;
use ReflectionClass;
use ReflectionEnum;
use ReflectionNamedType;
use ReflectionProperty;
use RuntimeException;

/**
 * Turns an authored entity subtree into a PHP prefab class.
 *
 * This is what "Save as Prefab" produces. The generated class extends
 * {@see Prefab}, so a scene references it by class name plus
 * override components and the engine rebuilds the geometry on load — the
 * compact, reference-carrying scene format, rather than a copy of the subtree
 * inlined into every scene that uses it.
 *
 * The root's placement (position/rotation/scale) is NOT baked in: it comes from
 * the instance via `getPosition()`/`getRotation()`/`getScale()`, so the same
 * prefab can be stamped anywhere. Everything else in the root's Transform3D
 * would be a per-instance value too, so it is dropped along with it.
 *
 * Values that a component's constructor cannot carry — a component that
 * declares its state as public `#[Property]` fields — are assigned after
 * construction. Without that an edited mesh graph or a sculpted heightmap would
 * come back empty, exactly the failure {@see DroppedPropertyDetector} reports
 * for scenes.
 *
 * Generated files carry a `@generated` marker plus a hash of their own body, so
 * {@see isRegenerable()} can tell a file the editor may replace from one that
 * has been edited by hand. Regenerating over the latter would silently eat
 * whatever logic was added to it — and hand-written logic is the whole reason
 * to have code prefabs rather than JSON snapshots.
 */
final class PrefabClassGenerator
{
    private const TRANSFORM3D = 'PHPolygon\\Component\\Transform3D';

    private const MARKER = '@generated by the PHPolygon editor';

    /** Indentation of statements inside the generated `build()` method. */
    private const BODY_INDENT = '        ';

    /** Classes the generated file always needs. */
    private const BASE_IMPORTS = [
        'PHPolygon\\Scene\\EntityDeclaration',
        'PHPolygon\\Scene\\Prefab',
        'PHPolygon\\Scene\\SceneBuilder',
    ];

    /** @var array<string, true> FQCNs the current run has to import. */
    private array $imports = [];

    /**
     * @param  array<string, mixed>  $entity  The authored subtree (name, components, children).
     */
    public function generate(array $entity, string $namespace, string $className): string
    {
        $this->imports = [];
        foreach (self::BASE_IMPORTS as $import) {
            $this->imports[$import] = true;
        }

        $body = $this->renderRoot($entity);
        $uses = $this->renderUses($namespace);
        $sourceName = is_string($entity['name'] ?? null) ? $entity['name'] : $className;

        $marker = $this->markerLine($sourceName);

        $source = <<<PHP
        <?php

        declare(strict_types=1);

        namespace {$namespace};

        {$uses}
        /**
         * {$marker}
         * @generated-hash {$this->hashPlaceholder()}
         *
         * Regenerated whenever the prefab is saved from the editor. Remove or
         * edit the marker above to take ownership of this file — the editor
         * then refuses to overwrite it instead of discarding your changes.
         */
        class {$className} extends Prefab
        {
            public function build(SceneBuilder \$builder): EntityDeclaration
            {
        {$body}
            }
        }

        PHP;

        // The hash covers the finished file with the placeholder still in it,
        // which is exactly what hashOf() reconstructs when verifying later.
        return str_replace($this->hashPlaceholder(), self::hashOf($source), $source);
    }

    private function hashPlaceholder(): string
    {
        return str_repeat('0', 16);
    }

    /**
     * Whether a generated file may be overwritten: it still carries the marker
     * and its body hash matches, i.e. nobody has edited it by hand.
     */
    public static function isRegenerable(string $source): bool
    {
        if (! str_contains($source, self::MARKER)) {
            return false;
        }

        if (preg_match('/@generated-hash ([0-9a-f]{16})/', $source, $m) !== 1) {
            return false;
        }

        return hash_equals($m[1], self::hashOf($source));
    }

    private function markerLine(string $sourceName): string
    {
        return self::MARKER.' from entity "'.$sourceName.'".';
    }

    /** Hash of the source with the hash value itself blanked out. */
    private static function hashOf(string $source): string
    {
        $normalised = (string) preg_replace(
            '/@generated-hash [0-9a-f]{16}/',
            '@generated-hash 0000000000000000',
            $source,
        );
        // Line endings are not content: a file checked out with CRLF must not
        // read as hand-edited.
        $normalised = str_replace("\r\n", "\n", $normalised);

        return substr(hash('sha256', $normalised), 0, 16);
    }

    /**
     * @param  array<string, mixed>  $entity
     */
    private function renderRoot(array $entity): string
    {
        $indent = self::BODY_INDENT;
        $lines = [$indent.'return $builder->entity($this->getInstanceName())'];

        // The root transform is the instance's placement, not authored data.
        $lines[] = $indent.'    ->with(new Transform3D('
            .'position: $this->getPosition(), '
            .'rotation: $this->getRotation(), '
            .'scale: $this->getScale()))';
        $this->imports[self::TRANSFORM3D] = true;

        foreach ($this->componentsOf($entity) as $component) {
            if (($component['_class'] ?? '') === self::TRANSFORM3D) {
                continue;
            }
            $lines[] = $indent.'    ->with('.$this->renderComponent($component).')';
        }

        foreach ($this->childrenOf($entity) as $child) {
            foreach ($this->renderChild($child, 1) as $line) {
                $lines[] = $line;
            }
        }

        return implode("\n", $lines).';';
    }

    /**
     * A child and its descendants as `->child(...)->with(...)->end()`.
     *
     * @param  array<string, mixed>  $child
     * @return list<string>
     */
    private function renderChild(array $child, int $depth): array
    {
        $indent = self::BODY_INDENT.str_repeat('    ', $depth);
        $name = is_string($child['name'] ?? null) ? $child['name'] : 'Child';

        $lines = [$indent.'->child('.var_export($name, true).')'];

        foreach ($this->componentsOf($child) as $component) {
            $lines[] = $indent.'    ->with('.$this->renderComponent($component).')';
        }

        foreach ($this->childrenOf($child) as $grandChild) {
            foreach ($this->renderChild($grandChild, $depth + 1) as $line) {
                $lines[] = $line;
            }
        }

        // Back up to the parent so the next sibling attaches at the right level.
        $lines[] = $indent.'->end()';

        return $lines;
    }

    /**
     * @param  array<string, mixed>  $component
     */
    private function renderComponent(array $component): string
    {
        $class = is_string($component['_class'] ?? null) ? $component['_class'] : '';
        if ($class === '' || ! class_exists($class)) {
            throw new RuntimeException(
                $class === ''
                    ? 'Component is missing its _class'
                    : "Component class not found: {$class}. Open the project so its classes are loadable."
            );
        }

        $this->imports[$class] = true;
        $short = $this->shortName($class);

        $args = $this->constructorArgs($class, $component);
        $expr = $args === [] ? "new {$short}" : "new {$short}(".implode(', ', $args).')';

        $assignments = $this->propertyAssignments($class, $component);
        if ($assignments === []) {
            return $args === [] ? $expr.'()' : $expr;
        }

        // A fluent ->with() chain has nowhere to put statements, so the values
        // the constructor cannot take are assigned inside an IIFE.
        $body = '$c = '.($args === [] ? $expr.'()' : $expr).';';
        foreach ($assignments as $assignment) {
            $body .= ' $c->'.$assignment['name'].' = '.$assignment['value'].';';
        }

        return "(static function (): {$short} { {$body} return \$c; })()";
    }

    /**
     * Named constructor arguments for the values the component carries.
     *
     * @param  array<string, mixed>  $data
     * @return list<string>
     */
    private function constructorArgs(string $class, array $data): array
    {
        $constructor = (new ReflectionClass($class))->getConstructor();
        if ($constructor === null) {
            return [];
        }

        $args = [];
        foreach ($constructor->getParameters() as $param) {
            $name = $param->getName();
            if (! array_key_exists($name, $data)) {
                continue;
            }

            $type = $param->getType();
            $rendered = $this->renderValue(
                $data[$name],
                $type instanceof ReflectionNamedType ? $type->getName() : null,
            );
            if ($rendered !== null) {
                $args[] = $name.': '.$rendered;
            }
        }

        return $args;
    }

    /**
     * Public writable properties the constructor did not already consume.
     *
     * @param  array<string, mixed>  $data
     * @return list<array{name: string, value: string}>
     */
    private function propertyAssignments(string $class, array $data): array
    {
        $reflection = new ReflectionClass($class);

        $consumed = [];
        $constructor = $reflection->getConstructor();
        if ($constructor !== null) {
            foreach ($constructor->getParameters() as $param) {
                $consumed[$param->getName()] = true;
            }
        }

        $assignments = [];
        foreach ($reflection->getProperties(ReflectionProperty::IS_PUBLIC) as $property) {
            $name = $property->getName();
            if ($property->isStatic() || $property->isReadOnly()) {
                continue;
            }
            if (isset($consumed[$name]) || ! array_key_exists($name, $data)) {
                continue;
            }

            // A value equal to the declared default carries no information.
            $value = $data[$name];
            if ($property->hasDefaultValue() && $property->getDefaultValue() == $value) {
                continue;
            }

            $type = $property->getType();
            $rendered = $this->renderValue($value, $type instanceof ReflectionNamedType ? $type->getName() : null);
            if ($rendered !== null) {
                $assignments[] = ['name' => $name, 'value' => $rendered];
            }
        }

        return $assignments;
    }

    /**
     * One value as a PHP literal, or null when it cannot be expressed.
     *
     * The declared type decides the shape: the document stores a Vec3 as
     * `{x, y, z}`, and only the type says whether that is a Vec3, a Color, or
     * a plain array.
     */
    private function renderValue(mixed $value, ?string $typeName): ?string
    {
        if ($value === null) {
            return 'null';
        }

        if ($typeName !== null && enum_exists($typeName)) {
            return $this->renderEnum($value, $typeName);
        }

        if ($typeName !== null && is_array($value) && class_exists($typeName)) {
            return $this->renderValueObject($value, $typeName);
        }

        // JSON has one number type, so a float-typed field arrives as an int
        // whenever its value happens to be whole. Render it by the DECLARED
        // type, or the generated file is littered with `new Vec3(0, 3.5, 0)`.
        if ($typeName === 'float' && (is_int($value) || is_float($value))) {
            return $this->renderFloat((float) $value);
        }

        if (is_bool($value) || is_int($value) || is_string($value)) {
            return var_export($value, true);
        }

        if (is_float($value)) {
            return $this->renderFloat($value);
        }

        if (is_array($value)) {
            return $this->renderArray($value);
        }

        return null;
    }

    /**
     * A value object the document stores as a map — Vec2/Vec3/Vec4, Color,
     * Quaternion, Rect. Its constructor parameter order defines the mapping.
     *
     * @param  array<string, mixed>  $value
     */
    private function renderValueObject(array $value, string $class): ?string
    {
        $constructor = (new ReflectionClass($class))->getConstructor();
        if ($constructor === null) {
            return null;
        }

        $args = [];
        foreach ($constructor->getParameters() as $param) {
            $name = $param->getName();
            if (! array_key_exists($name, $value)) {
                if ($param->isDefaultValueAvailable()) {
                    continue;
                }

                return null;
            }

            $type = $param->getType();
            $rendered = $this->renderValue(
                $value[$name],
                $type instanceof ReflectionNamedType ? $type->getName() : null,
            );
            if ($rendered === null) {
                return null;
            }
            $args[] = $rendered;
        }

        $this->imports[$class] = true;

        return 'new '.$this->shortName($class).'('.implode(', ', $args).')';
    }

    private function renderEnum(mixed $value, string $enumClass): ?string
    {
        if (! is_int($value) && ! is_string($value)) {
            return null;
        }

        $enum = new ReflectionEnum($enumClass);
        if (! $enum->isBacked()) {
            return null;
        }

        foreach ($enum->getCases() as $case) {
            $instance = $case->getValue();
            if ($instance instanceof BackedEnum && $instance->value === $value) {
                $this->imports[$enumClass] = true;

                return $this->shortName($enumClass).'::'.$case->getName();
            }
        }

        return null;
    }

    /**
     * @param  array<mixed>  $value
     */
    private function renderArray(array $value): string
    {
        $isList = array_is_list($value);
        $parts = [];
        foreach ($value as $key => $item) {
            $rendered = $this->renderValue($item, null);
            if ($rendered === null) {
                continue;
            }
            $parts[] = $isList ? $rendered : var_export($key, true).' => '.$rendered;
        }

        return '['.implode(', ', $parts).']';
    }

    private function renderFloat(float $value): string
    {
        if (is_nan($value) || is_infinite($value)) {
            return '0.0';
        }

        $rendered = var_export($value, true);

        return str_contains($rendered, '.') || str_contains($rendered, 'E')
            ? $rendered
            : $rendered.'.0';
    }

    /**
     * @param  array<string, mixed>  $entity
     * @return list<array<string, mixed>>
     */
    private function componentsOf(array $entity): array
    {
        $raw = is_array($entity['components'] ?? null) ? $entity['components'] : [];
        $components = [];
        foreach ($raw as $component) {
            if (is_array($component)) {
                $components[] = $component;
            }
        }

        return $components;
    }

    /**
     * @param  array<string, mixed>  $entity
     * @return list<array<string, mixed>>
     */
    private function childrenOf(array $entity): array
    {
        $raw = is_array($entity['children'] ?? null) ? $entity['children'] : [];
        $children = [];
        foreach ($raw as $child) {
            if (is_array($child)) {
                $children[] = $child;
            }
        }

        return $children;
    }

    /** Import block, skipping classes already in the prefab's own namespace. */
    private function renderUses(string $namespace): string
    {
        $imports = array_keys($this->imports);
        sort($imports);

        $lines = [];
        foreach ($imports as $fqcn) {
            if ($this->namespaceOf($fqcn) === $namespace) {
                continue;
            }
            $lines[] = 'use '.$fqcn.';';
        }

        return $lines === [] ? '' : implode("\n", $lines)."\n";
    }

    private function shortName(string $fqcn): string
    {
        $parts = explode('\\', $fqcn);

        return end($parts) ?: $fqcn;
    }

    private function namespaceOf(string $fqcn): string
    {
        $pos = strrpos($fqcn, '\\');

        return $pos === false ? '' : substr($fqcn, 0, $pos);
    }
}
