<?php

declare(strict_types=1);

/**
 * Regenerate the shared terrain-geometry fixture.
 *
 * The editor previews terrain with a TypeScript mesh builder while the engine
 * renders it with a PHP one. Those must agree, or an artist sculpts against
 * geometry the game will not reproduce. This script emits the engine's output
 * for a fixed heightmap; `TerrainMeshBuilderFixtureTest` (PHP) and
 * `engineParity.test.ts` (TypeScript) both assert against the result, so drift
 * on either side fails a test instead of silently shipping.
 *
 * Run after any intentional change to the geometry, and review the diff:
 *
 *     php scripts/generate-terrain-fixture.php
 */

require __DIR__.'/../vendor/autoload.php';

use PHPolygon\Terrain\HeightmapData;
use PHPolygon\Terrain\TerrainMeshBuilder;

// A small grid keeps the fixture readable, and an asymmetric one (9x5, uneven
// world extents) catches axis mix-ups that a square grid would hide.
$source = HeightmapData::fromFunction(
    static fn (float $x, float $z): float => sin($x * 0.35) * 4.0 + cos($z * 0.2) * 2.5,
    gridWidth: 9,
    gridDepth: 5,
    sizeX: 32.0,
    sizeZ: 16.0,
    minHeight: -10.0,
    maxHeight: 10.0,
);

// Build from the *quantised* heightmap, not the freshly sampled one. At runtime
// the engine always decodes a stored payload, so generating the fixture from
// full-precision samples would bake in geometry that neither implementation
// actually produces — a difference of up to one uint16 quantum per vertex.
$heightmap = HeightmapData::decode(
    $source->encode(),
    $source->gridWidth,
    $source->gridDepth,
    $source->sizeX,
    $source->sizeZ,
    $source->minHeight,
    $source->maxHeight,
);

$builder = new TerrainMeshBuilder;
$single = $builder->buildSingle($heightmap);

$chunks = [];
foreach ($builder->buildChunks($heightmap, 4) as $chunk) {
    $chunks[] = [
        'chunkX' => $chunk->chunkX,
        'chunkZ' => $chunk->chunkZ,
        'meshId' => $chunk->meshId('fixture'),
        'positions' => $chunk->mesh->vertices,
        'normals' => $chunk->mesh->normals,
        'uvs' => $chunk->mesh->uvs,
        'indices' => $chunk->mesh->indices,
    ];
}

$fixture = [
    '_comment' => 'Generated by scripts/generate-terrain-fixture.php — do not edit by hand.',
    'heightmap' => [
        'gridWidth' => $heightmap->gridWidth,
        'gridDepth' => $heightmap->gridDepth,
        'sizeX' => $heightmap->sizeX,
        'sizeZ' => $heightmap->sizeZ,
        'minHeight' => $heightmap->minHeight,
        'maxHeight' => $heightmap->maxHeight,
        'heights' => $heightmap->encode(),
    ],
    'single' => [
        'positions' => $single->vertices,
        'normals' => $single->normals,
        'uvs' => $single->uvs,
        'indices' => $single->indices,
    ],
    'chunks' => $chunks,
];

$path = __DIR__.'/../tests/fixtures/terrain-geometry.json';
if (! is_dir(dirname($path))) {
    mkdir(dirname($path), 0o755, true);
}

file_put_contents($path, json_encode($fixture, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n");

echo "Wrote {$path}\n";
echo 'single: '.$single->vertexCount()." vertices, {$single->triangleCount()} triangles\n";
echo 'chunks: '.count($chunks)."\n";
